name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
    STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.13

            - name: Install PDM
              run: pip install pdm

            - name: Install dependencies
              run: pdm install

            - name: Run linters
              run: pdm run linters

            - name: Run tests
              run: pdm run test

